### ISSUE TITLE
unable to perform db migration... help?

### ISSUE THREAD

**Issue by adm7373** [ericf/open-marriage#3]
[npm-debug.log.txt](https://github.com/ericf/open-marriage/files/96845/npm-debug.log.txt)

Hi Eric,

Thanks for putting this together, I'm planning on using it for my sister and her fiance's wedding.

When I try to run 'foreman run npm run migrate-up' it fails and I get the attached error output. Any ideas?

Thanks,
Andy

**Comment by ericf** [comment]
This project is an app, not a lib and not on npm. It looks like you're trying to install the app from the npm registry.
